# Generated by Django 4.2 on 2023-05-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorId',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('premiere_date', models.DateField(verbose_name='Дата премьеры')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='number',
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default=('M', 'Мужской'), max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='actor',
            name='actorid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actorid'),
        ),
        migrations.AddField(
            model_name='actor',
            name='creativeteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.creativeteam'),
        ),
        migrations.AddField(
            model_name='actor',
            name='plays',
            field=models.ManyToManyField(blank=True, to='core.play'),
        ),
    ]
