# Generated by Django 4.2 on 2023-05-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actorid_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='creativeteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='core.creativeteam'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='plays',
            field=models.ManyToManyField(blank=True, related_name='actors', to='core.play'),
        ),
    ]
