# Generated by Django 4.2 on 2023-05-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_actor_creativeteam_alter_actor_plays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actorid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actorid'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='creativeteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='core.creativeteam'),
        ),
    ]
