# Generated by Django 4.2 on 2023-06-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_actor_actorid_alter_actor_creativeteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={
                'ordering': ('actorid',),
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры'
            },
        ),
        migrations.AlterModelOptions(
            name='actorid',
            options={
                'ordering': ('number',),
                'verbose_name': 'ID-карта',
                'verbose_name_plural': 'ID-карты'
            },
        ),
        migrations.AlterModelOptions(
            name='creativeteam',
            options={
                'ordering': ('name',),
                'verbose_name': 'Творческая группа',
                'verbose_name_plural': 'Творческие группы'
            },
        ),
        migrations.AlterModelOptions(
            name='play',
            options={
                'ordering': ('title',),
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли'
            },
        ),
    ]
