# Generated by Django 4.2 on 2023-06-15 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_actor_options_alter_actorid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_data', message='Поле должно содержать только буквы', regex='^[a-zA-Z]*$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='second_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_data', message='Поле должно содержать только буквы', regex='^[a-zA-Z]*$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='actorid',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер'),
        ),
    ]
